services:
  fe:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /app/fe/dist:/usr/share/nginx/html/fe:ro
    depends_on:
      - be
    restart: unless-stopped

  be:
    image: us-east1-docker.pkg.dev/v1-mvp/be-dev/be:latest
    ports:
      - "8080:8080"
    env_file:
      - /app/be/.env
    restart: unless-stopped
