ppaDunFe:
  image: us-east1-docker.pkg.dev/v1-mvp/fe-prod/fe
  tag: "9d64a5261401ef482cebecd1c906ba8bdb91f043"
  replicas: 1
  port: 80

ppaDunBe:
  image: us-east1-docker.pkg.dev/v1-mvp/be-prod/be
  tag: "272fe51d04c9af7d58fc2d8e66c319ffb7aeea03"
  replicas: 1
  port: 8080

env: dev

ingress:
  host: ppa-dun.site
