ppaDunFe:
  image: us-east1-docker.pkg.dev/v1-mvp/fe-prod/fe
  tag: "801d0222e1b5a4ffade24af69f75100c2f5e95cd"
  replicas: 1
  port: 80

ppaDunBe:
  image: us-east1-docker.pkg.dev/v1-mvp/be-dev/be
  tag: "801d0222e1b5a4ffade24af69f75100c2f5e95cd"
  replicas: 1
  port: 8080

env: dev

ingress:
  host: ppa-dun.site
