ppaDunFe:
  image: us-east1-docker.pkg.dev/v1-mvp/fe-prod/fe
  tag: "8d8cec0e4cc65d47e6c9a048eda565f9f0298caa"
  replicas: 1
  port: 80

ppaDunBe:
  image: us-east1-docker.pkg.dev/v1-mvp/be-prod/be
  tag: "ef04cd79625f712c5ce84f35b478fb5e772fffaf"
  replicas: 1
  port: 8080

env: dev

ingress:
  host: ppa-dun.site
