apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-be
spec:
  replicas: {{ .Values.apiBe.replicas }}
  selector:
    matchLabels:
      app: api-be
  template:
    metadata:
      labels:
        app: api-be
    spec:
      containers:
        - name: api-be
          image: "{{ .Values.apiBe.image }}:{{ .Values.apiBe.tag }}"
          ports:
            - containerPort: {{ .Values.apiBe.port }}
          envFrom:
            - secretRef:
                name: app-secret
