apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ppa-dun-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ppa-dun-secret-store
    kind: SecretStore
  target:
    name: ppa-dun-secret
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_API_KEY
      remoteRef:
        key: external-api-key
    - secretKey: EXTERNAL_API_BASE_URL
      remoteRef:
        key: external-api-base-url
