apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ppa-dun-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ppa-dun-secret-store
    kind: SecretStore
  target:
    name: ppa-dun-secret
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_API_KEY
      remoteRef:
        key: external-api-key
    - secretKey: EXTERNAL_API_BASE_URL
      remoteRef:
        key: external-api-base-url
    - secretKey: DB_USER
      remoteRef:
        key: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: DB_HOST
      remoteRef:
        key: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: DB_NAME
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: DB_NAME
