apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ppa-dun-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: api-be
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-api
                port:
                  number: 80
