apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ppa-dun-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ppa-dun-lb"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ppa-dun-be
                port:
                  number: 80
