apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ppa-dun-secret-store
spec:
  provider:
    gcpsm:
      projectID: v2-ppa-dun
      auth:
        workloadIdentity:
          clusterLocation: us-east1
          clusterName: ppa-dun-cluster
          serviceAccountRef:
            name: ppa-dun-secrets-ksa
