apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: api-secret-store
    kind: SecretStore
  target:
    name: api-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: mysql-root-password
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: mysql-database
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: google-client-id
    - secretKey: EXTERNAL_API_KEY
      remoteRef:
        key: external-api-key
    - secretKey: EXTERNAL_API_BASE_URL
      remoteRef:
        key: external-api-base-url
